version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"

  consumer:
    build: ./consumer

  producer:
    build: ./producer
    ports:
      - "8080:8080"